version: 2
models:
 - name: dim_listings_cleansed
   description: Cleaned tables that contains listings. 
   columns:

      - name: listing_id
        description: Primary key for listing
        tests:
          - unique
          - not_null

      - name: host_id
        description: Points to host table
        tests:
          - not_null
          - relationships:
                to: ref('dim_hosts_cleansed')
                field: host_id

      - name: min_nights_booking
        tests:
          - positive_val          
 